// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Blog Post → Content*
 */
export interface BlogPostDefaultDocumentDataContentItem {
	/**
	 * Heading field in *Blog Post → Content*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.content[].heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * body field in *Blog Post → Content*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.content[].body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;
}

/**
 * Content for Blog Post documents
 */
interface BlogPostDefaultDocumentData {
	/**
	 * Banner field in *Blog Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.banner
	 * - **Tab**: Post
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	banner: prismic.ImageField<never>;

	/**
	 * Title field in *Blog Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.title
	 * - **Tab**: Post
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Subtitle field in *Blog Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.subtitle
	 * - **Tab**: Post
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;

	/**
	 * Author field in *Blog Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.author
	 * - **Tab**: Post
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	author: prismic.RichTextField;

	/**
	 * Content field in *Blog Post*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.content[]
	 * - **Tab**: Post
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	content: prismic.GroupField<Simplify<BlogPostDefaultDocumentDataContentItem>>;

	/**
	 * NextPost field in *Blog Post*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.nextpost
	 * - **Tab**: Post
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	nextpost: prismic.ContentRelationshipField<"blog_post_default">;

	/**
	 * PreviousPost field in *Blog Post*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_default.previouspost
	 * - **Tab**: Post
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	previouspost: prismic.ContentRelationshipField<"blog_post_default">;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post_default`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDefaultDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogPostDefaultDocumentData>,
	"blog_post_default",
	Lang
>;

export type AllDocumentTypes = BlogPostDefaultDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BlogPostDefaultDocument,
			BlogPostDefaultDocumentData,
			BlogPostDefaultDocumentDataContentItem,
			AllDocumentTypes,
		};
	}
}
