import { GoToTopButton } from "@/components/GoToTopButton";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme/NextThemeProvider";
import type { Metadata } from "next";
import "./globals.css";
import { Logo } from "@/components/Logo";
import { JetBrains_Mono } from "next/font/google";

const fontDefault = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body
				className={cn(
					"text-text ctp-latte min-h-screen bg-ctp-base dark:ctp-mocha sm:!p-5",
					fontDefault.className
				)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<main className="mx-auto max-w-screen-xl">
						<Logo className="mb-5 hidden text-center lg:block lg:text-left" />
						{children}
					</main>
					<GoToTopButton />
				</ThemeProvider>
			</body>
		</html>
	);
}
