import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme/NextThemeProvider";
import { DefaultPageHeader } from "@/components/DefaultPageHeader";
import { CardDefault } from "@/components/CardDefault";
import { ProfileResume } from "@/components/ProfileResume";
import { ReactQueryProvider } from "@/providers/ReactQuery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body
				className={cn(
					"text-text ctp-latte min-h-screen bg-ctp-base !p-5 dark:ctp-mocha",
					inter.className
				)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<ReactQueryProvider>
						<main className="mx-auto max-w-screen-xl">{children}</main>
					</ReactQueryProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
